### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mssmith63** [peterson-tim-j/Groundwater-Statistics-Toolbox#7]
Please consider including the following functions:
1. Cumulative monthly residual rainfall on same graph as groundwater level time series.
2. Statistics to compare the likeness and lag of these two plots.
3. Removal of fluctuations in groundwater level time series due to barometric pressure and Earth tides, and graphical presentation and verbal indication of cumulative response behaviour as per Rasmussen and Crawford 1997 Groundwater 35/3 pp. 502-511, Spane 2002 Water Resources Research 35/6 pp. 1-17, and Toll and Rasmussen 2007 Ground Water 45/1 pp. 101-105, to identify degree of aquifer confinement, lag time, other aquifer properties if possible, and well-bore storage and skin effects.
Dr. Michael S. Smith, Hydrogeologist, NSW DPI-Water.

**Comment by peterson-tim-j** [comment]
Request has been disaggregated into two individual requests.
